"""Typed application services for graver clients.

This module is the supported pre-1.0 import boundary for application code. It
contains no CLI, terminal-rendering, Qt, SQLite connection, or third-party HTTP
types. The initial synchronous workspace façade composes these same request, result,
error, and service objects rather than replacing their domain meaning.

Examples:
    Open a database and query its research queue without global configuration::

        from graver.application import ResearchTaskQuery, open_workspace

        workspace = open_workspace("research.db")
        tasks = workspace.work.list(ResearchTaskQuery(limit=10))
"""

from graver.acquisition import (
    AcquisitionFieldChange,
    AcquisitionReceipt,
    MemorialSearchFailed,
    MemorialSummaryBatch,
    MemorialSummaryInput,
    MemorialSummarySearchRequest,
    SummaryAcquisitionService,
)
from graver.database import (
    DatabaseInitializationError,
    DatabaseInspectionError,
    DatabaseLifecycleError,
    DatabaseUpgradeError,
    DatabaseUpgradeResult,
    SchemaInspection,
    create_database,
    inspect_database,
    upgrade_database,
    validate_current_database,
)
from graver.errors import ApplicationError, DatabaseBusy, DatabaseOperationError
from graver.evidence import (
    AssessmentRecord,
    AssessmentUpdate,
    CandidateInput,
    CandidateSnapshotRecord,
    ComparisonSignalInput,
    ComparisonSignalRecord,
    ConclusionRecord,
    ConclusionRequest,
    DiscoveryRequest,
    DiscoveryResult,
    EvidenceError,
    EvidenceInputError,
    EvidenceNotFound,
    EvidenceService,
    RankedCandidate,
    SourceObservationInput,
    SourceObservationRecord,
    StaleAssessment,
)
from graver.progress import (
    CancellationRequested,
    CancellationToken,
    ProgressEvent,
    ProgressObserver,
)
from graver.research import (
    DisplayedRelationshipInput,
    EnrichmentAliasBlocked,
    EnrichmentFailed,
    EnrichmentNotApproved,
    EnrichmentRedirected,
    EnrichmentRedirectInvalid,
    MemorialDetailInput,
    ResearchEnrichmentRequest,
    ResearchEnrichmentResult,
    ResearchInputError,
    ResearchQueueRequest,
    ResearchQueueResult,
    ResearchService,
    ResearchTaskDetail,
    ResearchTaskQuery,
    ResearchTaskRecord,
    ResearchTaskSummary,
    ResearchTaskUpdate,
    StaleResearchTask,
)
from graver.workspace import (
    GraverWorkspace,
    WorkItemNotFound,
    WorkspaceAcquisition,
    WorkspaceDatabase,
    WorkspaceWork,
    open_workspace,
)

__all__ = (
    "AcquisitionFieldChange",
    "AcquisitionReceipt",
    "ApplicationError",
    "AssessmentRecord",
    "AssessmentUpdate",
    "CancellationRequested",
    "CancellationToken",
    "CandidateInput",
    "CandidateSnapshotRecord",
    "ComparisonSignalInput",
    "ComparisonSignalRecord",
    "ConclusionRecord",
    "ConclusionRequest",
    "DatabaseInitializationError",
    "DatabaseBusy",
    "DatabaseInspectionError",
    "DatabaseLifecycleError",
    "DatabaseOperationError",
    "DatabaseUpgradeError",
    "DatabaseUpgradeResult",
    "DiscoveryRequest",
    "DiscoveryResult",
    "DisplayedRelationshipInput",
    "EnrichmentAliasBlocked",
    "EnrichmentFailed",
    "EnrichmentNotApproved",
    "EnrichmentRedirectInvalid",
    "EnrichmentRedirected",
    "EvidenceError",
    "EvidenceInputError",
    "EvidenceNotFound",
    "EvidenceService",
    "GraverWorkspace",
    "MemorialDetailInput",
    "MemorialSearchFailed",
    "MemorialSummaryBatch",
    "MemorialSummaryInput",
    "MemorialSummarySearchRequest",
    "ProgressEvent",
    "ProgressObserver",
    "RankedCandidate",
    "ResearchEnrichmentRequest",
    "ResearchEnrichmentResult",
    "ResearchInputError",
    "ResearchQueueRequest",
    "ResearchQueueResult",
    "ResearchService",
    "ResearchTaskDetail",
    "ResearchTaskQuery",
    "ResearchTaskRecord",
    "ResearchTaskSummary",
    "ResearchTaskUpdate",
    "SchemaInspection",
    "SourceObservationInput",
    "SourceObservationRecord",
    "StaleAssessment",
    "StaleResearchTask",
    "SummaryAcquisitionService",
    "WorkItemNotFound",
    "WorkspaceAcquisition",
    "WorkspaceDatabase",
    "WorkspaceWork",
    "create_database",
    "inspect_database",
    "open_workspace",
    "upgrade_database",
    "validate_current_database",
)
