[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[project]
name = "graver"
version = "0.1.0"
description = ""
authors = [{ name = "Larry McQueary", email = "contact@mcqueary.org" }]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "beautifulsoup4>=4.12,<5",
    "tqdm>=4.66.3,<5",
    "typer>=0.12,<1",
    "requests>=2.33,<3",
]

[project.scripts]
graver = "graver.cli:app"

[dependency-groups]
test = [
    "click>=8.1,<9",
    "flake8>=7,<8",
    "pytest>=9.0.3,<10",
    "pytest-cov>=7.1.0,<8",
    "pytest-helpers-namespace>=2021.12.29,<2022",
    "pytest-integration>=0.2.3,<0.3",
    "python-dateutil>=2.9,<3",
    "requests-mock>=1.11.0,<2",
    "betamax>=0.8.1,<1",
    "faker>=21",
]
dev = [
    "black>=24.3,<27",
    "isort>=5.12.0,<7",
    "pre-commit>=3.5.0,<5",
    "mypy>=1.7.1,<2",
    "types-beautifulsoup4>=4.12.0.7,<5",
    "types-tqdm>=4.66.0.5,<5",
    "deadcode>=2.2.2,<3",
    "types-requests>=2.31.0.10,<3",
    "types-python-dateutil>=2.8.19.14,<3",
]

[tool.deadcode]
exclude = [".venv", ".tox", ".trunk", "tests"]
ignore-names = ["BaseTestCase", "*Mixin"]
ignore-names-in-files = ["migrations"]

[tool.black]
target-version = ["py311", "py312", "py313", "py314"]


[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning:betamax.*"]

[tool.coverage.run]
branch = true
source = ["graver"]

[tool.coverage.report]
fail_under = 90
show_missing = true
skip_covered = true

[tool.coverage.xml]
output = "coverage.xml"
